"""About_This_Blog_Post

Revision ID: 2609503dea20
Revises: cca51eb5fdc0
Create Date: 2018-12-03 11:23:32.042606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2609503dea20'
down_revision = 'cca51eb5fdc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about__this__blog__post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about__this__blog__post')
    # ### end Alembic commands ###
